nodes:
  data:
    node_builder:
      _target_: anemoi.graphs.nodes.ZarrDatasetNodes
      dataset:
        cutout:
          - dataset: regional-dataset.zarr
            thinning: 25
          - dataset: /path/to/global-dataset.zarr
        adjust: all
        min_distance_km: 10
    attributes:
      cutout_mask:
        _target_: anemoi.graphs.nodes.attributes.CutOutMask
  hidden:
    node_builder:
      _target_: anemoi.graphs.nodes.LimitedAreaTriNodes
      resolution: 5
      reference_node_name: data
      mask_attr_name: cutout_mask
    attributes: ...

edges: ...
