nodes:
  data:
    node_builder:
      _target_: anemoi.graphs.nodes.ZarrDatasetNodes
      dataset: /path/to/dataset.zarr
    attributes:
      weights:
        _target_: anemoi.graphs.nodes.attributes.AreaWeights
        norm: unit-max
  hidden: ...
