nodes:
  data:
    node_builder:
      _target_: anemoi.graphs.nodes.ZarrDatasetNodes
      # ...
    attributes:
      land_mask:
        _target_: anemoi.graphs.nodes.attributes.NonmissingZarrVariable
        variable: lsm
  hidden: ...
