nodes:
  data:
    node_builder: ...
    attributes:
      weights:
        _target_: anemoi.graphs.nodes.attributes.AreaWeights # options: AreaWeights, UniformWeights
        norm: unit-max # options: unit-max, unit-range, unit-std
  hidden: ...
